# ==========================================
# DEVELOPMENT
# ==========================================

server.port=8080

# ==========================================
# DATABASE - Some properties is moved to parameter stores
# ==========================================java -XX:+PrintFlagsFinal -version

# spring.datasource.url=jdbc:postgresql://localhost:5432/cases
# spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


spring.datasource.url=jdbc:postgresql://localhost:5432/cases
spring.datasource.username=caseuser
spring.datasource.password=casepassword
spring.datasource.driver-class-name=org.postgresql.Driver

# ==========================================
# HIKARI CONNECTION POOL - Moved to paramter store
# ==========================================

# spring.datasource.hikari.maximum-pool-size=5
# spring.datasource.hikari.minimum-idle=2
# spring.datasource.hikari.connection-timeout=500

# ==========================================
# LOGGING
# ==========================================

logging.level.root=INFO
logging.level.com.example.case_viewer=DEBUG

logging.level.org.springframework.web=INFO
logging.level.org.springframework.transaction=DEBUG

# ==========================================
# DATABASE / JPA
# ==========================================

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE

# ==========================================
# FILE
# ==========================================

logging.file.name=logs/case-viewer-dev.log

# ==========================================
# LOG ROTATION
# ==========================================

logging.logback.rollingpolicy.max-file-size=10MB
logging.logback.rollingpolicy.max-history=30
logging.logback.rollingpolicy.total-size-cap=1GB


# ==========================================
# JWT
# ==========================================
jwt.secret=your-very-long-secret-key-for-development-only-change-this
jwt.expiration=3600000


# ==========================================
# Redis Cache
# ==========================================
spring.cache.type=redis
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.cache.redis.enable-statistics=true




# ==========================================
# Secrets Data
# ==========================================
#spring.config.import=\
# aws-secretsmanager:case-viewer/db,\
# aws-secretsmanager:case-viewer/redis,\
# aws-parameterstore:/case-viewer/


spring.config.import=\
 aws-secretsmanager:case-viewer/redis,\
 aws-parameterstore:/case-viewer/